#define MINUTE (60000)
#define SECOND (1000)

#define GAMETICK (250)
#define HALF_TICK (GAMETICK / 2)

#define ROUND_MINI (MINUTE / 2)
#define ROUND_SHORT (5 * MINUTE)
#define ROUND_REGULAR (10 * MINUTE)
#define ROUND_LONG (15 * MINUTE)
#define ROUND_EXTREME (30 * MINUTE)

#define BEEP_DURATION (HALF_TICK * 0.87)

#define REQUIRED_DEFUSE_TIME (SECOND * 10)
